services:
  saul-spot:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn -w 2 -b 0.0.0.0:8000 app:app
    volumes:
      - ./transcripts:/app/transcripts
    networks:
      - site_network

networks:
  site_network:
    external: true
