services:
  saul-spot:
    container_name: saul-spot
    build: .
    ports:
      - ${SAUL_SPOT_SERVER_PORT}:8000
    command: gunicorn -w 2 -b 0.0.0.0:8000 app:app
    volumes:
      - ./transcripts:/app/transcripts