services:
  saul-spot:
    build: .
    command: gunicorn -w 2 -b 0.0.0.0:8000 app:app
    volumes:
      - ./transcripts:/app/transcripts

  cloudflared:
    restart: unless-stopped
    image: cloudflare/cloudflared:latest
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
